In [2]:
import numpy as np
from PIL import Image

In [3]:
data_input = np.genfromtxt("camera_y.log", delimiter=',')  
data_input = np.uint8(data_input)

print(data_input)
print(data_input.shape)

img = Image.fromarray(data_input, 'L')
img.save('my_gray.png')
img.show()

[[105 104 104 ...  67  64  61]
 [104 104 103 ...  66  74  66]
 [103 104 105 ...  66  66  67]
 ...
 [ 78  80  81 ...  47  49  51]
 [ 80  81  83 ...  49  50  49]
 [ 76  77  77 ...  52  47  49]]
(480, 640)
