In [1]:
from scipy.io.wavfile import write
import numpy as np

samplerate = 16000;

In [2]:
data_input = np.genfromtxt("pcm_dual.log", delimiter=',')  
print(data_input)

[[ 0.00000e+00  8.03000e+02  5.20000e+01]
 [ 1.00000e+00  9.29900e+03  9.49300e+03]
 [ 2.00000e+00 -4.11000e+02  5.62000e+02]
 ...
 [ 2.28797e+05 -1.74900e+03 -3.11500e+03]
 [ 2.28798e+05 -4.20300e+03 -9.50900e+03]
 [ 2.28799e+05  2.84000e+02  7.30400e+03]]


In [3]:
data_input = data_input.T
print(data_input)

[[ 0.00000e+00  1.00000e+00  2.00000e+00 ...  2.28797e+05  2.28798e+05
   2.28799e+05]
 [ 8.03000e+02  9.29900e+03 -4.11000e+02 ... -1.74900e+03 -4.20300e+03
   2.84000e+02]
 [ 5.20000e+01  9.49300e+03  5.62000e+02 ... -3.11500e+03 -9.50900e+03
   7.30400e+03]]


In [4]:
data_serial_number = data_input[0]
print(data_serial_number)

[0.00000e+00 1.00000e+00 2.00000e+00 ... 2.28797e+05 2.28798e+05
 2.28799e+05]


In [5]:
left_channel = data_input[1]
print(left_channel)

[  803.  9299.  -411. ... -1749. -4203.   284.]


In [6]:
right_channel = data_input[2]
print(right_channel)

[   52.  9493.   562. ... -3115. -9509.  7304.]


In [7]:
dual_channel = left_channel + right_channel
dual_channel = dual_channel / 2
print(dual_channel)

[  427.5  9396.     75.5 ... -2432.  -6856.   3794. ]


In [8]:
write("pcm16_example.wav", samplerate, dual_channel.astype(np.int16))